# Generated by Django 3.2 on 2022-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('Phones', 'Phones'), ('1', '1'), ('2', '2'), ('2', '2')], max_length=50)),
                ('Description', models.CharField(max_length=500)),
                ('Price', models.PositiveBigIntegerField(default=0)),
                ('Image', models.ImageField(upload_to='media/products')),
            ],
        ),
    ]
