# Generated by Django 3.2 on 2022-06-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='Category',
            field=models.CharField(choices=[('Phones', 'Phones'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=50),
        ),
    ]
