# Generated by Django 3.2 on 2022-07-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220630_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=100)),
                ('Phone_num', models.IntegerField()),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Address', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.items')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
