# Generated by Django 3.2 on 2022-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220707_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
