# Generated by Django 4.1 on 2022-08-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220709_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Category',
            field=models.CharField(choices=[('Phones', 'Phones'), ('Accessories', 'Accessories'), ('Sneakers', 'Sneakers'), ('Others', 'Others')], max_length=50),
        ),
    ]
